language: emacs-lisp
env:
  - EMACS_VERSION=24.5
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  - emacs --version

  # ycmd
  - git clone --depth=1 --recursive https://github.com/Valloric/ycmd
  - cd ycmd
  - python build.py --clang-completer --gocode-completer
  - cd ..

install:
  - make deps
script:
  - make all
  - make YCMDPATH="ycmd/ycmd" test

